# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: resolve sudo timeout
  become: yes
  shell: "echo 127.0.1.1       $(cat /etc/hostname) >> /etc/hosts"

- name: make interface config file
  become: yes
  template:
    src=interface.cfg.j2
    dest="{{source_path}}/config/interface.cfg" owner=root group=root mode=755

- name: make static_arp config file
  become: yes
  template:
    src=static_arp.cfg.j2
    dest="{{source_path}}/config/static_arp.cfg" owner=root group=root mode=755

- name: get date
  shell: date +"%Y-%m-%d_%H-%M"
  register: tmp_date

- name: get port_0 value
  shell: "ifconfig | grep -B 1 {{ s1u_ip }} | awk '{print $1}' | head -n 1"
  register: tmp_port_0

- name: get port_1 value
  shell: "ifconfig | grep -B 1 {{ sgi_ip }} | awk '{print $1}' | head -n 1"
  register: tmp_port_1

- name: get s1u_mac value
  shell: "ifconfig | grep -B 2 {{ s1u_ip }} | grep HWaddr | awk \'{print $5}\'"
  register: tmp_s1u_mac

- name: get sgi_mac value
  shell: "ifconfig | grep -B 2 {{ sgi_ip }} | grep HWaddr | awk \'{print $5}\'"
  register: tmp_sgi_mac

- name: assign results into each variable
  set_fact:
    port_0: "{{ tmp_port_0.stdout }}"
    port_1: "{{ tmp_port_1.stdout }}"
    s1u_mac: "{{ tmp_s1u_mac.stdout }}"
    sgi_mac: "{{ tmp_sgi_mac.stdout }}"
    date: "{{ tmp_date.stdout }}"

- name: make dp_config config file
  become: yes
  template:
    src=dp_config.cfg.j2
    dest="{{source_path}}/config/dp_config.cfg" owner=root group=root mode=755

- name: change Makefile.j2
  become: yes
  template:
    src=Makefile.j2
    dest="{{source_path}}/dp/Makefile" owner=root group=root mode=755

- name: write flag for interface_config
  become: yes
  shell: "echo 1 > {{source_path}}/dp/finish_flag_interface_config"